import type { Metadata } from "next";
import Navbar from '@/components/navbar'

export const metadata: Metadata = {
  title: "iNote - Edit a new Note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        <Navbar/>
        {children}
    </div>
  );
}
